<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="base" params="length width height mass wheel_radius wheel_pos_z mesh_file">
    
    <link name="base_footprint"/>
    
    <link name="base_link">
      <visual>
        <origin xyz="0 0 ${height/2 - wheel_radius}" rpy="0 0 0"/>
        <geometry>
          <xacro:if value="${mesh_file == ''}">
            <box size="${length} ${width} ${height}"/>
          </xacro:if>
          <xacro:unless value="${mesh_file == ''}">
            <mesh filename="${mesh_file}" scale="1 1 1"/>
          </xacro:unless>
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 ${height/2 - wheel_radius}" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 ${height/2 - wheel_radius}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>

    <gazebo reference="base_link">  
      <visual>  
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>  
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>  
          <specular>0.99 0.99 0.99 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual> 
    </gazebo>

    <joint name="base_to_footprint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

<!-- ====================================================== Wheels ============================================ -->

  <xacro:macro name="wheel" params="side radius width pos_x pos_y pos_z mass mesh_file">
    <link name="${side}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <xacro:if value="${mesh_file == ''}">
            <cylinder radius="${radius}" length="${width}"/>
          </xacro:if>
          <xacro:unless value="${mesh_file == ''}">
            <mesh filename="${mesh_file}" scale="1 1 1"/>
          </xacro:unless>
        </geometry>
        <material name="blue">
            <color rgba="0.1764 0.4588 0.8509 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(2/5) * mass * (radius * radius)}" ixy="0" ixz="0"
                 iyy="${(2/5) * mass * (radius * radius)}" iyz="0"
                 izz="${(2/5) * mass * (radius * radius)}" />
      </inertial>
    </link>
    <gazebo reference="${side}_wheel_link">  
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>10000000.0</kp>
      <kd>1.0</kd>
      <visual>  
        <material>
          <ambient>0.1764 0.4588 0.8509 1.0</ambient>  
          <diffuse>0.1764 0.4588 0.8509 1.0</diffuse>  
          <specular>0.1764 0.4588 0.8509 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual>  
    </gazebo>
    <joint name="${side}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" />
      <parent link="base_link"/>
      <child link="${side}_wheel_link"/>
      <origin xyz="${pos_x} ${pos_y} ${pos_z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

<!-- ======================================================  Castor Wheels ============================================ -->

  <xacro:macro name="caster_wheel" params="side mass base_length base_width wheel_radius wheel_pos_z">
    <xacro:property name="caster_wheel_radius" value="${(wheel_radius - wheel_pos_z) / 2}" />

    <!-- ADD "base_length" IN THE 'params' LIST, IF YOU WANT TO UNCOMMENT THE FOLLOWING 
    (N.B: this snippet is taken from linorobot2, and is not reuired in servera) -->

    <xacro:if value="${side == 'right'}">
        <xacro:property name="caster_wheel_x" value="-${(base_length / 2) - caster_wheel_radius}" />
        <xacro:property name="caster_wheel_y" value="-${(base_width / 2) - caster_wheel_radius}" />
      </xacro:if>
    
    <xacro:if value="${side == 'left'}">
        <xacro:property name="caster_wheel_x" value="-${(base_length / 2) - caster_wheel_radius}" />
        <xacro:property name="caster_wheel_y" value="${(base_width / 2) - caster_wheel_radius}" />
    </xacro:if>
    

    
    <link name="${side}_caster_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}" />
        </geometry>
        <material name="black">
            <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(2/5) * mass * (caster_wheel_radius * caster_wheel_radius)}" ixy="0" ixz="0"
                 iyy="${(2/5) * mass * (caster_wheel_radius * caster_wheel_radius)}" iyz="0"
                 izz="${(2/5) * mass * (caster_wheel_radius * caster_wheel_radius)}" />
      </inertial>
    </link>

    <gazebo reference="${side}_caster_wheel_link">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>

    <joint name="${side}_caster_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${side}_caster_wheel_link"/>
      <origin xyz=" ${caster_wheel_x} ${caster_wheel_y} -${caster_wheel_radius}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

</robot>